### ISSUE TITLE
Using Z3 SMT solver

### ISSUE THREAD

**Issue by soffensive** [altjx/ipwn#5]
Thanks for your great work. 
I enhanced your program to use the Z3 SMT solver for generating the correct sequence of summands, instead of utilizing the random function. 

Have a look:

https://github.com/soffensive/subencoder-z3

**Comment by altjx** [comment]
Hi @soffensive,

Pretty late post here, but it doesn't look like the link is currently working. Let me know if there's any additional questions or suggestions. Thanks for the help, and sorry for the delay.
