### ISSUE TITLE
ismtp should switch to Python 3

### ISSUE THREAD

**Issue by rhertzog** [altjx/ipwn#8]
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).

Since Kali Linux is based on Debian Testing, we have to follow along. And since istmp.py is part of Kali, we would like to have a version of that script that works with Python 3.

Can you update the script for Python 3 please ? A quick run of 2to3 would likely fix most of the issues.

Tracking bug in Kali: https://gitlab.com/kalilinux/packages/ismtp/issues/1

**Comment by altjx** [comment]
Hi @rhertzog,

This should now be resolved. Please let me know if there's anything else I need to do.
